POST  http://localhost:4002/product
Content-type: application/json

{
    "name": "Caneta vermelha",
    "price": 5
}

###

GET http://localhost:4002/products

###
GET http://localhost:4002/products/

###
PUT http://localhost:4002/products/
Content-type: application/json

{
    "name": "Caneta azul",
    "price": 15.00
}
###
DELETE  http://localhost:4002/products/